spring.application.name=inventario

server.port=8080

# 1. PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://db:5432/inventariodb
# Ensure these match your Postgres credentials (usually not 'sa' for Postgres)
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Disable H2 Console (It won't work with PostgreSQL)
spring.h2.console.enabled=false
